# Generated by Django 4.2.16 on 2025-09-27 04:23
# Fix for admin log user_id type conversion that was incorrectly setting values to NULL

from django.db import migrations, connection


def fix_admin_log_user_id_properly(apps, schema_editor):
    """
    Properly fix django_admin_log.user_id type to UUID without setting values to NULL
    """
    # Only run on PostgreSQL - SQLite tests don't need this
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        # Check if column is already UUID
        cursor.execute("""
            SELECT data_type
            FROM information_schema.columns
            WHERE table_name = 'django_admin_log'
            AND column_name = 'user_id'
        """)
        current_type = cursor.fetchone()

        if current_type and current_type[0] == 'uuid':
            return  # Already fixed

        # Determine the correct table reference based on environment
        cursor.execute("SELECT current_schema();")
        current_schema = cursor.fetchone()[0]

        if current_schema == 'public':
            users_table = 'users'
        else:
            users_table = 'auth.users'

        # Clear existing data to avoid conversion issues
        cursor.execute("DELETE FROM django_admin_log;")

        # Drop foreign key constraint
        cursor.execute("ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey CASCADE;")

        # Change column type from integer to UUID (corrected - no USING NULL)
        cursor.execute("ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE UUID;")

        # Re-add foreign key constraint with correct table reference
        cursor.execute(f"""
            ALTER TABLE django_admin_log
            ADD CONSTRAINT django_admin_log_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES {users_table}(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
        """)


def reverse_fix_admin_log_user_id_properly(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_fix_admin_log_user_id'),
    ]

    operations = [
        migrations.RunPython(
            fix_admin_log_user_id_properly,
            reverse_fix_admin_log_user_id_properly,
        ),
    ]