# Generated by Django 4.2.16 on 2025-09-27 04:38
# Reset admin migrations to fix UUID User model compatibility

from django.db import migrations, connection
from django.core.management import call_command


def reset_admin_migrations_for_uuid_user(apps, schema_editor):
    """
    Reset admin migrations to properly handle UUID User model.
    This is the definitive fix for django_admin_log user_id type mismatch.
    """
    # Only run on PostgreSQL
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        # Check if fix is needed
        cursor.execute("""
            SELECT data_type
            FROM information_schema.columns
            WHERE table_name = 'django_admin_log'
            AND column_name = 'user_id'
        """)
        current_type = cursor.fetchone()

        if current_type and current_type[0] == 'uuid':
            return  # Already fixed

        # Drop the problematic table
        cursor.execute('DROP TABLE IF EXISTS django_admin_log CASCADE;')

    # Reset and re-apply admin migrations
    # This will recreate django_admin_log with correct UUID foreign key
    call_command('migrate', 'admin', 'zero', '--fake', verbosity=0)
    call_command('migrate', 'admin', verbosity=0)


def reverse_reset_admin_migrations(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_fix_admin_log_user_id_v2'),
    ]

    operations = [
        migrations.RunPython(
            reset_admin_migrations_for_uuid_user,
            reverse_reset_admin_migrations,
        ),
    ]