# Generated by Django 4.2.16 on 2025-09-27 04:42
# Working fix for admin log UUID issue - based on successful local fix

from django.db import migrations, connection
from django.core.management import call_command


def working_admin_log_fix(apps, schema_editor):
    """
    Apply the working fix that was successful locally.
    This replicates the reset_admin_log management command logic.
    """
    # Only run on PostgreSQL
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        # Check if table exists and current type
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'django_admin_log'
            );
        """)
        table_exists = cursor.fetchone()[0]

        if table_exists:
            # Check current user_id type
            cursor.execute("""
                SELECT data_type
                FROM information_schema.columns
                WHERE table_name = 'django_admin_log'
                AND column_name = 'user_id'
            """)
            current_type = cursor.fetchone()

            if current_type and current_type[0] == 'uuid':
                return  # Already fixed

            # Drop the problematic table completely
            cursor.execute('DROP TABLE IF EXISTS django_admin_log CASCADE;')

    # Reset admin migrations and recreate table with correct UUID type
    call_command('migrate', 'admin', 'zero', '--fake', verbosity=0)
    call_command('migrate', 'admin', verbosity=0)


def reverse_working_admin_log_fix(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_reset_admin_migrations'),
    ]

    operations = [
        migrations.RunPython(
            working_admin_log_fix,
            reverse_working_admin_log_fix,
        ),
    ]
