# Generated by Django 4.2.16 on 2025-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
