# Generated by Django 4.2.16 on 2025-12-13 13:02

from django.db import migrations, models


def update_plan_values(apps, schema_editor):
    """
    Update existing plan values to match new plan names:
    - free -> starter
    - professional -> growth
    - enterprise -> enterprise (no change)
    """
    User = apps.get_model('authentication', 'User')

    # Update free to starter
    User.objects.filter(plan='free').update(plan='starter')

    # Update professional to growth
    User.objects.filter(plan='professional').update(plan='growth')

    # enterprise stays the same


def reverse_plan_values(apps, schema_editor):
    """
    Reverse the plan value updates:
    - starter -> free
    - growth -> professional
    - enterprise -> enterprise (no change)
    """
    User = apps.get_model('authentication', 'User')

    # Reverse starter to free
    User.objects.filter(plan='starter').update(plan='free')

    # Reverse growth to professional
    User.objects.filter(plan='growth').update(plan='professional')


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_plan'),
    ]

    operations = [
        # First, update the data before changing the field constraints
        migrations.RunPython(update_plan_values, reverse_plan_values),

        # Then update the field definition
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
    ]
