# Generated by Django 4.2.16 on 2025-12-19 20:56

import apps.authentication.db_mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_update_plan_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(help_text='SHA256 hash of the 6-digit reset code', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expires after 1 hour')),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the token has been used successfully')),
                ('is_invalidated', models.BooleanField(default=False, help_text='Whether the token was invalidated (max attempts)')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='password_re_user_id_af59e2_idx'), models.Index(fields=['code_hash'], name='password_re_code_ha_498509_idx'), models.Index(fields=['expires_at'], name='password_re_expires_8e96b7_idx')],
            },
            bases=(apps.authentication.db_mixins.RetryableModelMixin, models.Model),
        ),
    ]
