# Generated by Django 5.2.5 on 2025-12-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(default=False, help_text='Flag indicating user must change their password on next login (e.g., temporary password from Stripe setup)'),
        ),
    ]
