# Generated by Django 4.2.16 on 2025-12-21 21:08

import apps.authentication.db_mixins
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_requires_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitee_email', models.EmailField(help_text='Email address of the person being invited', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('developer', 'Developer')], default='developer', help_text='Role for the invited user', max_length=50)),
                ('token', models.CharField(help_text='Unique invitation token', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expires after 7 days')),
                ('is_accepted', models.BooleanField(default=False, help_text='Whether the invitation has been accepted')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('accepted_by', models.ForeignKey(blank=True, db_column='accepted_by_id', help_text='User who accepted the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='authentication.company')),
                ('inviter', models.ForeignKey(db_column='inviter_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='company_inv_company_20dc17_idx'), models.Index(fields=['invitee_email'], name='company_inv_invitee_e3dfd5_idx'), models.Index(fields=['token'], name='company_inv_token_a333e7_idx'), models.Index(fields=['expires_at'], name='company_inv_expires_60cc22_idx')],
            },
            bases=(apps.authentication.db_mixins.RetryableModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='companyinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2025, 12, 21, 21, 8, 32, 91778, tzinfo=datetime.timezone.utc)), ('is_accepted', False)), fields=('company', 'invitee_email'), name='unique_active_invitation_per_email_company'),
        ),
    ]
