# Generated by Django 4.2.16 on 2026-01-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_fix_companyinvitation_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, help_text='GitHub username from OAuth login', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gitlab_username',
            field=models.CharField(blank=True, help_text='GitLab username from OAuth login', max_length=100, null=True),
        ),
    ]
